language: node_js

node_js:
  - "stable"

install:
  - npm install

script: 
  - npm test
after_success: npm run coverage

notifications:
  email: false
services:
  - postgresql
before_script:
  - psql -c 'create database politico;' -U postgres

cache:
  directories:
    - 'node_modules'
